---
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.6
    container_name: weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    ports:
    - 8032:8080
    - 50052:50051
    volumes:
      - ./data/weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
      DISK_USE_READONLY_PERCENTAGE: 99
      DISK_USE_WARNING_PERCENTAGE: 95
      AUTOSCHEMA_ENABLED: 'false'



